# ==========================================
# Application
# ==========================================
spring.application.name=hirenest-backend


# ==========================================
# MySQL Database
# ==========================================
spring.datasource.url=JDBC:mysql://localhost:3306/hirenest
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ==========================================
# Server
# ==========================================
server.port=8080

#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.operations-sorter=method
#springdoc.swagger-ui.tags-sorter=alpha

app.jwt.secret=VGhpc0lzQVNlY3VyZVNlY3JldEtleUZvckhpcmVOZXN0MjAyNg==
app.jwt.expiration-ms=86400000