spring.application.name=hiesnest

spring.datasource.url=jdbc:mysql://localhost:3306/hirenestdb
spring.datasource.username=root
spring.datasource.password=Kandha@27

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true