# ==========================================
# APPLICATION
# ==========================================
spring.application.name=hiesnest

# ==========================================
# SERVER
# ==========================================
server.port=8081

# ==========================================
# MYSQL DATABASE
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/probatio
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ==========================================
# SWAGGER / OPENAPI
# ==========================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================================
# JWT
# ==========================================
app.jwt.secret=Q6GPHtb+aE6Uk/JgHlZk6Eq9jLGjGjsATlxFQuKOn6M=
app.jwt.expiration-ms=3600000

# ==========================================
# OTP
# ==========================================
app.otp.expiration-minutes=5
app.otp.max-attempts=5

# ==========================================
# GMAIL SMTP
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tech.sunny1@gmail.com
spring.mail.password=Sunny@123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true